# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
    build:
        # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
        # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
        machine:
            # Specify the version you desire here
            # See: https://circleci.com/developer/images/image/cimg/base
            image: ubuntu-2004:current
        resource_class: medium

        # Add steps to the job
        # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
        steps:
            # Checkout the code as the first step.
            - checkout

            - run: |
                  TAG=0.1.$CIRCLE_BUILD_NUM
                  docker build -t casteljeremy/backspace-academy:$TAG .
                  docker run --rm -d -p 8080:8080 --name backspace casteljeremy/backspace-academy:$TAG
                  sleep 5
                  ip -4 addr
                  curl http://example.org
                  docker stop backspace
                  # echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                  # docker push casteljeremy/backspace-academy:$TAG

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
    build-docker-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
        # Inside the workflow, you define the jobs you want to run.
        jobs:
            - build

